=== hypercube1024/firefly/firefly-slf4j/src/main/java/com/firefly/utils/log/loggers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.fireflysource.com/loggers"
        xmlns:logger="http://www.fireflysource.com/loggers"
        elementFormDefault="qualified">

    <element name="logger">
        <complexType>
            <sequence>
                <element name="name" type="string" minOccurs="1" maxOccurs="1"/>
                <element name="level" type="string" minOccurs="0" maxOccurs="1" default="INFO"/>
                <element name="path" type="string" minOccurs="0" maxOccurs="1"/>
                <element name="enable-console" type="string" minOccurs="0" maxOccurs="1" default="false"/>
                <element name="max-file-size" type="string" minOccurs="0" maxOccurs="1" default="209715200"/>
                <element name="charset" type="string" minOccurs="0" maxOccurs="1" default="UTF-8"/>
                <element name="formatter" type="string" minOccurs="0" maxOccurs="1" default="com.firefly.utils.log.DefaultLogFormatter"/>
            </sequence>
        </complexType>
    </element>

    <!-- root element -->
    <element name="loggers">
        <complexType>
            <sequence>
                <element ref="logger:logger" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
</schema>

=== hypercube1024/firefly/firefly-boot/src/main/resources/firefly-log.xml
<?xml version="1.0" encoding="UTF-8"?>
<loggers xmlns="http://www.fireflysource.com/loggers"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.fireflysource.com/loggers http://www.fireflysource.com/loggers.xsd">
    <logger>
        <name>firefly-system</name>
        <level>INFO</level>
        <enable-console>true</enable-console>
        <formatter>com.firefly.boot.common.BootLogFormatter</formatter>
    </logger>

    <logger>
        <name>com.firefly.boot</name>
        <level>INFO</level>
        <enable-console>true</enable-console>
        <formatter>com.firefly.boot.common.BootLogFormatter</formatter>
    </logger>

</loggers>

=== hypercube1024/firefly/firefly-slf4j/src/test/resources/firefly-log.xml
<?xml version="1.0" encoding="UTF-8"?>
<loggers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.fireflysource.com/loggers"
         xsi:schemaLocation="http://www.fireflysource.com/loggers http://www.fireflysource.com/loggers.xsd">

    <logger>
        <name>firefly-common</name>
        <level>${log.level}</level>
        <path>${log.path}</path>
        <enable-console>true</enable-console>
    </logger>

    <logger>
        <name>test-TRACE</name>
        <level>TRACE</level>
        <path>${log.path}</path>
        <enable-console>true</enable-console>
    </logger>

    <logger>
        <name>test-DEBUG</name>
        <level>DEBUG</level>
        <path>${log.path}</path>
        <enable-console>true</enable-console>
    </logger>

    <logger>
        <name>test-ERROR</name>
        <level>ERROR</level>
        <path>${log.path}</path>
        <enable-console>true</enable-console>
    </logger>

    <logger>
        <name>test-WARN</name>
        <level>WARN</level>
        <path>${log.path}</path>
        <enable-console>false</enable-console>
    </logger>

    <logger>
        <name>test-INFO</name>
        <level>INFO</level>
        <path>${log.path}</path>
        <enable-console>false</enable-console>
    </logger>

    <logger>
        <name>test-console</name>
        <level>INFO</level>
        <enable-console>true</enable-console>
    </logger>

    <logger>
        <name>firefly-system</name>
        <level>INFO</level>
        <enable-console>true</enable-console>
    </logger>

    <logger>
        <name>com.fireflysource.log.foo</name>
        <level>INFO</level>
        <path>${log.path}</path>
        <enable-console>true</enable-console>
    </logger>

    <logger>
        <name>com.fireflysource.log.foo.bar</name>
        <level>INFO</level>
        <path>${log.path}</path>
        <enable-console>true</enable-console>
    </logger>

    <logger>
        <name>test.max.size</name>
        <level>INFO</level>
        <path>${log.path}</path>
        <max-file-size>300</max-file-size>
        <charset>UTF-8</charset>
    </logger>

    <logger>
        <name>test.gbk</name>
        <level>INFO</level>
        <path>${log.path}</path>
        <charset>GBK</charset>
    </logger>

    <logger>
        <name>test-request-id</name>
        <level>INFO</level>
        <path>${log.path}</path>
    </logger>

    <logger>
        <name>com.fireflysource.log.demo</name>
        <level>${log.level}</level>
        <path>${log.path}</path>
        <enable-console>true</enable-console>
        <formatter>com.fireflysource.log.demo.CustomLogFormatter</formatter>
    </logger>

    <logger>
        <name>time-split-minute</name>
        <level>INFO</level>
        <path>${log.path}</path>
        <max-split-time>minute</max-split-time>
    </logger>
</loggers>
