=== hypercube1024/firefly/beans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:bean="http://www.fireflysource.com/beans"
        targetNamespace="http://www.fireflysource.com/beans"
        elementFormDefault="qualified">

    <element name="import">
        <complexType>
            <attribute name="resource"/>
        </complexType>
    </element>
    <element name="component-scan">
        <complexType>
            <attribute name="base-package"/>
        </complexType>
    </element>
    <element name="value">
        <complexType mixed="true">
            <attribute name="type"/>
        </complexType>
    </element>
    <element name="ref">
        <complexType>
            <attribute name="bean"/>
        </complexType>
    </element>
    <element name="list">
        <complexType>
            <group ref="bean:collectionElements"/>
            <attribute name="type"/>
        </complexType>
    </element>
    <element name="array">
        <complexType>
            <group ref="bean:collectionElements"/>
        </complexType>
    </element>
    <element name="map">
        <complexType>
            <sequence>
                <element name="entry" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="key" minOccurs="0" maxOccurs="1">
                                <complexType mixed="true">
                                    <group ref="bean:mapElements"/>
                                </complexType>
                            </element>
                            <element name="value" minOccurs="0" maxOccurs="1">
                                <complexType mixed="true">
                                    <group ref="bean:mapElements"/>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="key"/>
                        <attribute name="value"/>
                    </complexType>
                </element>
            </sequence>
            <attribute name="type"/>
        </complexType>
    </element>
    <element name="bean">
        <complexType>
            <sequence>
                <element name="constructor" minOccurs="0" maxOccurs="1">
                    <complexType>
                        <sequence>
                            <element name="argument" minOccurs="0" maxOccurs="unbounded">
                                <complexType>
                                    <group ref="bean:propertyElements"/>
                                    <attribute name="value"/>
                                    <attribute name="ref"/>
                                    <attribute name="type" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="property" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <group ref="bean:propertyElements"/>
                        <attribute name="name" use="required"/>
                        <attribute name="value"/>
                        <attribute name="ref"/>
                    </complexType>
                </element>
            </sequence>
            <attribute name="id"/>
            <attribute name="class"/>
            <attribute name="init-method"/>
            <attribute name="destroy-method"/>
        </complexType>
    </element>


    <!-- root element -->
    <element name="beans">
        <complexType>
            <sequence>
                <element ref="bean:import" minOccurs="0" maxOccurs="unbounded"/>
                <element ref="bean:component-scan" minOccurs="0" maxOccurs="unbounded"/>
                <element ref="bean:bean" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
        <unique name="idUnique">
            <selector xpath="bean:bean"/>
            <field xpath="@id"/>
        </unique>
        <!-- <key name="beanKey">
            <selector xpath=".//bean:bean"></selector>
            <field xpath="@id"></field>
        </key>
        <keyref name="refKey" refer="bean:beanKey">
            <selector xpath=".//bean:ref"></selector>
            <field xpath="@bean"></field>
        </keyref>
        <keyref name="beanRefKey" refer="bean:beanKey">
            <selector xpath=".//bean:property"></selector>
            <field xpath="@ref"></field>
        </keyref> -->
    </element>

    <group name="collectionElements">
        <sequence>
            <choice minOccurs="0" maxOccurs="unbounded">
                <element ref="bean:value"/>
                <element ref="bean:ref"/>
                <element ref="bean:list"/>
                <element ref="bean:array"/>
                <element ref="bean:map"/>
            </choice>
        </sequence>
    </group>
    <group name="propertyElements">
        <sequence>
            <choice minOccurs="0" maxOccurs="1">
                <element ref="bean:value"/>
                <element ref="bean:ref"/>
                <element ref="bean:list"/>
                <element ref="bean:array"/>
                <element ref="bean:map"/>
            </choice>
        </sequence>
    </group>
    <group name="mapElements">
        <sequence>
            <choice minOccurs="0" maxOccurs="1">
                <element ref="bean:ref"/>
                <element ref="bean:list"/>
                <element ref="bean:array"/>
                <element ref="bean:map"/>
            </choice>
        </sequence>
    </group>
</schema>

=== hypercube1024/firefly/firefly/src/test/resources/testImport.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <import resource="testImport1.xml"/>

    <bean id="person" class="test.component3.Person">
        <property name="name" value="Jack"/>
        <property name="age" value="12"/>
    </bean>
    <bean id="person2" class="test.component3.Person">
        <property name="name">
            <value>Bob</value>
        </property>
        <property name="age" value="32"/>
    </bean>

</beans>

=== hypercube1024/firefly/firefly/src/test/resources/mixed-constructor.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <import resource="mixed-config2.xml"/>
    <import resource="mixed-config3.xml"/>
    <import resource="mixed-config4.xml"/>
    <component-scan base-package="test.mixed"/>

    <bean id="foodRepository" class="test.mixed.impl.FoodRepositoryImpl">
        <constructor>
            <argument type="java.util.List">
                <list>
                    <ref bean="apple"/>
                    <ref bean="orange"/>
                    <ref bean="strawberry"/>
                </list>
            </argument>
        </constructor>
    </bean>

    <bean id="constructorTestBean" class="test.ioc.TestConstructorsIoc$BeanTest">
        <constructor>
            <argument type="java.lang.String" value="fffff"></argument>
            <argument type="java.lang.Integer" value="4"></argument>
        </constructor>
    </bean>

    <bean id="foodService2" class="test.mixed.impl.FoodService2Impl">

        <property name="foodService">
            <ref bean="foodService"/>
        </property>
    </bean>

</beans>
