=== hypercube1024/firefly/beans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:bean="http://www.fireflysource.com/beans"
        targetNamespace="http://www.fireflysource.com/beans"
        elementFormDefault="qualified">

    <element name="import">
        <complexType>
            <attribute name="resource"/>
        </complexType>
    </element>
    <element name="component-scan">
        <complexType>
            <attribute name="base-package"/>
        </complexType>
    </element>
    <element name="value">
        <complexType mixed="true">
            <attribute name="type"/>
        </complexType>
    </element>
    <element name="ref">
        <complexType>
            <attribute name="bean"/>
        </complexType>
    </element>
    <element name="list">
        <complexType>
            <group ref="bean:collectionElements"/>
            <attribute name="type"/>
        </complexType>
    </element>
    <element name="array">
        <complexType>
            <group ref="bean:collectionElements"/>
        </complexType>
    </element>
    <element name="map">
        <complexType>
            <sequence>
                <element name="entry" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="key" minOccurs="0" maxOccurs="1">
                                <complexType mixed="true">
                                    <group ref="bean:mapElements"/>
                                </complexType>
                            </element>
                            <element name="value" minOccurs="0" maxOccurs="1">
                                <complexType mixed="true">
                                    <group ref="bean:mapElements"/>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="key"/>
                        <attribute name="value"/>
                    </complexType>
                </element>
            </sequence>
            <attribute name="type"/>
        </complexType>
    </element>
    <element name="bean">
        <complexType>
            <sequence>
                <element name="constructor" minOccurs="0" maxOccurs="1">
                    <complexType>
                        <sequence>
                            <element name="argument" minOccurs="0" maxOccurs="unbounded">
                                <complexType>
                                    <group ref="bean:propertyElements"/>
                                    <attribute name="value"/>
                                    <attribute name="ref"/>
                                    <attribute name="type" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="property" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <group ref="bean:propertyElements"/>
                        <attribute name="name" use="required"/>
                        <attribute name="value"/>
                        <attribute name="ref"/>
                    </complexType>
                </element>
            </sequence>
            <attribute name="id"/>
            <attribute name="class"/>
            <attribute name="init-method"/>
            <attribute name="destroy-method"/>
        </complexType>
    </element>


    <!-- root element -->
    <element name="beans">
        <complexType>
            <sequence>
                <element ref="bean:import" minOccurs="0" maxOccurs="unbounded"/>
                <element ref="bean:component-scan" minOccurs="0" maxOccurs="unbounded"/>
                <element ref="bean:bean" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
        <unique name="idUnique">
            <selector xpath="bean:bean"/>
            <field xpath="@id"/>
        </unique>
        <!-- <key name="beanKey">
            <selector xpath=".//bean:bean"></selector>
            <field xpath="@id"></field>
        </key>
        <keyref name="refKey" refer="bean:beanKey">
            <selector xpath=".//bean:ref"></selector>
            <field xpath="@bean"></field>
        </keyref>
        <keyref name="beanRefKey" refer="bean:beanKey">
            <selector xpath=".//bean:property"></selector>
            <field xpath="@ref"></field>
        </keyref> -->
    </element>

    <group name="collectionElements">
        <sequence>
            <choice minOccurs="0" maxOccurs="unbounded">
                <element ref="bean:value"/>
                <element ref="bean:ref"/>
                <element ref="bean:list"/>
                <element ref="bean:array"/>
                <element ref="bean:map"/>
            </choice>
        </sequence>
    </group>
    <group name="propertyElements">
        <sequence>
            <choice minOccurs="0" maxOccurs="1">
                <element ref="bean:value"/>
                <element ref="bean:ref"/>
                <element ref="bean:list"/>
                <element ref="bean:array"/>
                <element ref="bean:map"/>
            </choice>
        </sequence>
    </group>
    <group name="mapElements">
        <sequence>
            <choice minOccurs="0" maxOccurs="1">
                <element ref="bean:ref"/>
                <element ref="bean:list"/>
                <element ref="bean:array"/>
                <element ref="bean:map"/>
            </choice>
        </sequence>
    </group>
</schema>

=== hypercube1024/firefly/firefly/src/test/resources/firefly.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <import resource="testImport.xml"/>

    <bean id="personService" class="test.component3.PersonService" init-method="init">
        <property name="person" ref="person"/>
        <property name="testList">
            <list>
                <value type="int">123</value>
                <ref bean="person2"/>
                <value type="java.lang.String">dfdf</value>
                <ref bean="person"/>
                <map>
                    <entry key="2.2" value="3.3"/>
                    <entry>
                        <key>
                            dddd
                        </key>
                        <value>
                            <array>
                                <value>11</value>
                                <value>12</value>
                                <value>11.5</value>
                            </array>
                        </value>
                    </entry>
                </map>
            </list>
        </property>
        <property name="testList2">
            <list>
                <value type="java.lang.String">a1</value>
                <value type="java.lang.String">a2</value>
            </list>
        </property>
    </bean>

    <bean id="collectionService3" class="test.component3.CollectionService">
        <property name="strArray">
            <array>
                <value>str1</value>
                <value>str2</value>
                <value type="java.lang.String">3</value>
            </array>
        </property>
    </bean>

    <bean id="collectionService4" class="test.component3.CollectionService">
        <property name="intArray">
            <array>
                <value>1022</value>
                <value>1032</value>
                <value>1042</value>
            </array>
        </property>
    </bean>

    <bean id="collectionService5" class="test.component3.CollectionService">
        <property name="objArray">
            <array>
                <value>1022</value>
                <value>1032</value>
                <value>dddddd</value>
                <array>
                    <ref bean="person2"/>
                    <value>10000000000</value>
                </array>
            </array>
        </property>
    </bean>

    <bean id="mapService" class="test.component3.MapService">
        <property name="map">
            <map>
                <entry key="1" value="www"/>
                <entry>
                    <key>ddd</key>
                    <value>sfsfsfsf</value>
                </entry>
                <entry>
                    <key>
                        <ref bean="person"/>
                    </key>
                    <value>ssss</value>
                </entry>
                <entry>
                    <key>
                        <list>
                            <value>sssss</value>
                        </list>
                    </key>
                    <value>234444444</value>
                </entry>
                <entry>
                    <key>
                        <array>
                            <value>sssss</value>
                            <value>sssss3</value>
                            <value>sssss4</value>
                        </array>
                    </key>
                    <value>
                        <map>
                            <entry>
                                <key>ssss</key>
                                <value>
                                    <list>
                                        <value>12345</value>
                                        <value>67890</value>
                                        <ref bean="person"/>
                                    </list>
                                </value>
                            </entry>
                        </map>
                    </value>
                </entry>
            </map>
        </property>
    </bean>

</beans>

=== hypercube1024/firefly/firefly-example/src/main/resources/java-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <import resource="datasource.xml"/>

    <component-scan base-package="com.firefly.example.reactive.coffee.store.utils"/>
    <component-scan base-package="com.firefly.example.reactive.coffee.store.dao"/>
    <component-scan base-package="com.firefly.example.reactive.coffee.store.service"/>
    <component-scan base-package="com.firefly.example.reactive.coffee.store.router"/>

    <bean id="localSessionHandler" class="com.firefly.server.http2.router.handler.session.LocalHTTPSessionHandler"
          destroy-method="stop"/>

    <bean id="projectConfig" class="com.firefly.example.reactive.coffee.store.ProjectConfig">
        <property name="templateRoot" value="template/coffeeStore"/>
        <property name="host" value="localhost"/>
        <property name="port" value="8080"/>
    </bean>

    <bean id="reactiveMain" class="com.firefly.example.reactive.coffee.store.AppMain"/>

    <bean id="reactiveSQLClient" class="com.firefly.reactive.adapter.db.ReactiveSQLClientAdapter">
        <constructor>
            <argument type="com.firefly.db.SQLClient" ref="jdbcClient"/>
        </constructor>
    </bean>

    <bean id="httpServer" class="com.firefly.server.http2.HTTP2ServerBuilder"
          init-method="httpServer"
          destroy-method="stop"/>


</beans>

=== hypercube1024/firefly/firefly/src/test/resources/mixed-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <import resource="mixed-config2.xml"/>
    <import resource="mixed-config3.xml"/>
    <import resource="mixed-config4.xml"/>
    <component-scan base-package="test.mixed"/>

    <bean id="foodRepository" class="test.mixed.impl.FoodRepositoryImpl">
        <property name="food">
            <list>
                <ref bean="apple"/>
                <ref bean="orange"/>
                <ref bean="strawberry"/>
            </list>
        </property>
    </bean>

    <bean id="foodService2" class="test.mixed.impl.FoodService2Impl">
        <property name="foodService">
            <ref bean="foodService"/>
        </property>
    </bean>

    <bean id="kebab" class="test.mixed.Snack">
        <property name="productionPlace" value="China"/>
        <property name="relish" value="peppery"/>
        <property name="name" value="mmp"/>
        <property name="price" value="3.5"/>
    </bean>

</beans>

=== hypercube1024/firefly/firefly-example/src/main/resources/kotlin-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <import resource="datasource.xml"/>

    <component-scan base-package="com.firefly.example.kotlin.coffee"/>

    <bean id="localSessionHandler" class="com.firefly.server.http2.router.handler.session.LocalHTTPSessionHandler"
          destroy-method="stop"/>

    <bean id="asyncHttpContextTransactionalManager"
          class="com.firefly.kotlin.ext.db.AsyncCoroutineContextTransactionalManager">
        <constructor>
            <argument type="com.firefly.db.SQLClient" ref="jdbcClient"/>
        </constructor>
    </bean>

    <bean id="ktHttpServer" class="com.firefly.kotlin.ext.http.HttpServer"/>

    <bean id="ktProjectConfig" class="com.firefly.example.kotlin.coffee.store.ProjectConfig">
        <property name="templateRoot" value="template/coffeeStore"/>
        <property name="host" value="localhost"/>
        <property name="port" value="8080"/>
        <property name="loginURL" value="/login"/>
        <property name="logoutURL" value="/logout"/>
        <property name="loginUserKey" value="_loginUser"/>
        <property name="sessionMaxInactiveInterval" value="1800"/>
    </bean>

    <bean id="ktMain" class="com.firefly.example.kotlin.coffee.store.AppMain"/>
</beans>

=== hypercube1024/firefly/firefly-kotlin-ext/src/test/resources/firefly.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <component-scan base-package="com.firefly.kotlin.ext.context" />
    <component-scan base-package="com.firefly.kotlin.ext.example.task.management" />

    <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource">
        <property name="jdbcUrl" value="jdbc:h2:mem:test" />
        <property name="driverClassName" value="org.h2.Driver" />
        <property name="isAutoCommit" value="false" />
    </bean>

    <bean id="jdbcClient" class="com.firefly.db.jdbc.JDBCClient" destroy-method="stop">
        <constructor>
            <argument type="javax.sql.DataSource" ref="dataSource"/>
        </constructor>
    </bean>

    <bean id="httpCoroutineLocal" class="com.firefly.kotlin.ext.common.CoroutineLocal"/>

    <bean id="asyncHttpContextTransactionalManager" class="com.firefly.kotlin.ext.db.AsyncHttpContextTransactionalManager">
        <constructor>
            <argument type="com.firefly.kotlin.ext.common.CoroutineLocal" ref="httpCoroutineLocal"/>
            <argument type="com.firefly.db.SQLClient" ref="jdbcClient"/>
        </constructor>
    </bean>

</beans>

=== hypercube1024/firefly/firefly/src/test/resources/firefly2.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <bean id="collectionService" class="test.component3.CollectionService">
        <property name="list">
            <list>
                <value>s1</value>
                <value>s2</value>
            </list>
        </property>
        <property name="set">
            <list>
                <value type="int">3</value>
                <value type="int">3</value>
                <value type="java.lang.String">4sss</value>
            </list>
        </property>
    </bean>

    <!-- <bean id="collectionService" class="test.component3.CollectionService">
        <property name="list">
            <list>
                <value>s1</value>
                <value>s2</value>
                <list type="java.util.HashSet">
                    <value>s3</value>
                    <value>s4</value>
                    <value>s4</value>
                </list>
            </list>
        </property>
        <property name="set">
            <list>
                <value type="int">3</value>
                <value type="int">3</value>
                <value type="int">4</value>
            </list>
        </property>
    </bean> -->

</beans>

=== hypercube1024/firefly/firefly-example/src/main/resources/datasource.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource">
        <property name="jdbcUrl" value="jdbc:h2:mem:coffee_store"/>
        <property name="driverClassName" value="org.h2.Driver"/>
        <property name="isAutoCommit" value="false"/>
    </bean>

    <bean id="jdbcClient" class="com.firefly.db.jdbc.JDBCClient" destroy-method="stop">
        <constructor>
            <argument type="javax.sql.DataSource" ref="dataSource"/>
        </constructor>
    </bean>

</beans>

=== hypercube1024/firefly/firefly-example/src/main/resources/hello-ioc.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.fireflysource.com/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.fireflysource.com/beans http://www.fireflysource.com/beans.xsd">

    <component-scan base-package="com.firefly.example.ioc"/>

    <bean id="helloService" class="com.firefly.example.ioc.HelloServiceImpl">
        <property name="message" value="Hello IOC"/>
    </bean>

    <bean id="barService" class="com.firefly.example.ioc.BarServiceImpl" init-method="init" destroy-method="destroy">
        <property name="fooService" ref="fooService"/>
        <property name="foods">
            <list>
                <value>fish</value>
                <value>Cola</value>
                <value>whisky</value>
            </list>
        </property>
        <property name="foodPrices">
            <map>
                <entry key="fish" value="15.00"/>
                <entry key="Cola" value="2.5"/>
                <entry key="whisky" value="20.99"/>
            </map>
        </property>
        <property name="barName" value="BarRR"/>
    </bean>

</beans>
